In [1]:
from getpass import getpass
usuario = input('Tu usuario de GitHub: ')
token = getpass('Pegá tu token: ')
!git clone https://{usuario}:{token}@github.com/{usuario}/Cloud-Provider-Analytics-G2.git
%cd Cloud-Provider-Analytics-G2

Tu usuario de GitHub: camimattioli
Pegá tu token: ··········
Cloning into 'Cloud-Provider-Analytics-G2'...
remote: Enumerating objects: 76, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 76 (delta 35), reused 9 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (76/76), 142.25 KiB | 3.65 MiB/s, done.
Resolving deltas: 100% (35/35), done.
/content/Cloud-Provider-Analytics-G2

In [20]:
import pandas as pd

df = pd.read_csv('data/raw/customers_orgs.csv')
df.head()

,org_id,org_name,industry,hq_region,plan_tier,is_enterprise,signup_date,sales_rep,lifecycle_stage,marketing_source,nps_score
0,org_xaji0y6d,Nimbus Labs 0,Education,sa-east,standard,True,2025-05-26,rep_c,churned,partner,NaN
1,org_pbhsahxt,Nova Tech 1,Education,us-east,standard,False,2025-06-16,rep_d,lead,event,-3.0
2,org_hv3a3zmf,Gamma Data 2,Media,eu-central,pro,True,2025-05-12,rep_c,active,organic,4.0
3,org_8mdd4v30,Apex Data 3,Manufacturing,sa-east,standard,False,2025-05-30,rep_b,active,ads,12.0
4,org_t9nt3w5u,Delta Digital 4,E-commerce,us-west,standard,False,2025-05-16,rep_d,active,partner,17.0

In [21]:
df.tail()

,org_id,org_name,industry,hq_region,plan_tier,is_enterprise,signup_date,sales_rep,lifecycle_stage,marketing_source,nps_score
75,org_dzr1yxr2,Beta AI 75,E-commerce,eu-west,standard,False,2025-05-24,rep_d,at_risk,organic,-38.0
76,org_dhylurtp,Nimbus Cloud 76,Fintech,ap-south,pro,False,2025-05-29,rep_d,active,organic,NaN
77,org_0lzjjege,Alpha Cloud 77,Media,eu-west,standard,False,2025-07-02,rep_e,active,referral,-7.0
78,org_t1ghr09s,Beta Cloud 78,Gaming,sa-east,standard,False,2025-06-06,rep_a,active,event,11.0
79,org_kdgigatj,Zenith Tech 79,Gaming,ap-northeast,standard,False,2025-06-29,rep_d,active,referral,10.0

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   org_id            80 non-null     object
 1   org_name          80 non-null     object
 2   industry          80 non-null     object
 3   hq_region         80 non-null     object
 4   plan_tier         80 non-null     object
 5   is_enterprise     80 non-null     bool
 6   signup_date       80 non-null     object
 7   sales_rep         80 non-null     object
 8   lifecycle_stage   80 non-null     object
 9   marketing_source  80 non-null     object
 10  nps_score         69 non-null     float64
dtypes: bool(1), float64(1), object(9)
memory usage: 6.5+ KB

In [23]:
#Convertir signup_date a formato fecha, venía como obj
df['signup_date'] = pd.to_datetime(df['signup_date'])
df['signup_date']

0    2025-05-26
1    2025-06-16
2    2025-05-12
3    2025-05-30
4    2025-05-16
        ...
75   2025-05-24
76   2025-05-29
77   2025-07-02
78   2025-06-06
79   2025-06-29
Name: signup_date, Length: 80, dtype: datetime64[ns]

In [24]:
df.isnull().sum()

org_id               0
org_name             0
industry             0
hq_region            0
plan_tier            0
is_enterprise        0
signup_date          0
sales_rep            0
lifecycle_stage      0
marketing_source     0
nps_score           11
dtype: int64

In [25]:
df['nps_score'].describe()

count     69.000000
mean      18.666667
std       26.071546
min      -38.000000
25%        1.000000
50%       14.000000
75%       34.000000
max      101.000000
Name: nps_score, dtype: float64

In [26]:
df[df['nps_score'] > 100]

,org_id,org_name,industry,hq_region,plan_tier,is_enterprise,signup_date,sales_rep,lifecycle_stage,marketing_source,nps_score
37,org_pac56t4u,Gamma Cloud 37,Healthcare,eu-central,enterprise,False,2025-05-21,rep_a,active,partner,101.0

Se detectó un valor de 101 en `nps_score`, matemáticamente imposible ya que el NPS
tiene un rango válido de -100 a 100. Se interpretó como error de carga y se convirtió
a NaN, sumándose al resto de los valores faltantes de la columna.

In [27]:
df.loc[df['nps_score'] > 100, 'nps_score'] = None

In [29]:
df[df['nps_score'] < 0]

,org_id,org_name,industry,hq_region,plan_tier,is_enterprise,signup_date,sales_rep,lifecycle_stage,marketing_source,nps_score
1,org_pbhsahxt,Nova Tech 1,Education,us-east,standard,False,2025-06-16,rep_d,lead,event,-3.0
18,org_pht0hl9x,Nimbus Data 18,Government,eu-central,pro,False,2025-05-09,rep_a,active,referral,-4.0
19,org_pseimvih,Vertex Data 19,Fintech,eu-central,standard,False,2025-05-30,rep_d,active,event,-7.0
20,org_cwi64ciy,Gamma Digital 20,Media,ap-northeast,standard,False,2025-06-07,rep_e,active,event,-28.0
21,org_he7ur23g,Alpha Labs 21,Gaming,eu-central,free,False,2025-06-13,rep_a,at_risk,referral,-1.0
22,org_dppq0y9d,Vertex Labs 22,Manufacturing,ap-south,standard,False,2025-06-26,rep_c,at_risk,partner,-1.0
23,org_om5igqpk,Beta Cloud 23,Energy,sa-east,pro,False,2025-05-23,rep_b,active,ads,-17.0
26,org_n9j2qp89,Nova AI 26,Retail,us-west,standard,False,2025-05-30,rep_b,churned,organic,-2.0
34,org_x7eedtjv,Apex Cloud 34,Energy,ap-south,pro,True,2025-06-10,rep_b,active,partner,-6.0
45,org_0lvsnujz,Nova Cloud 45,Retail,us-east,standard,False,2025-05-19,rep_e,prospect,event,-1.0
48,org_okep7y6w,Alpha Labs 48,Education,ap-northeast,enterprise,False,2025-05-08,rep_e,at_risk,ads,-13.0
52,org_ir4cowgz,Delta Tech 52,Manufacturing,us-east,standard,False,2025-06-29,rep_e,at_risk,referral,-8.0
54,org_g8sbi4q2,Zenith AI 54,Gaming,ap-south,standard,False,2025-05-14,rep_e,lead,organic,-33.0
57,org_1swjckjl,Beta Tech 57,Government,eu-west,standard,True,2025-06-03,rep_e,active,organic,-4.0
75,org_dzr1yxr2,Beta AI 75,E-commerce,eu-west,standard,False,2025-05-24,rep_d,at_risk,organic,-38.0
77,org_0lzjjege,Alpha Cloud 77,Media,eu-west,standard,False,2025-07-02,rep_e,active,referral,-7.0

In [30]:
pd.crosstab(
    df["nps_score"].isnull(),
    df["lifecycle_stage"]
)

lifecycle_stage  active  at_risk  churned  lead  prospect
nps_score
False                47       10        5     2         4
True                  7        1        1     1         2

In [31]:
print("Sin NPS:")
print(df[df['nps_score'].isnull()]['signup_date'].describe())

print("\nCon NPS:")
print(df[df['nps_score'].notnull()]['signup_date'].describe())

Sin NPS:
count                     12
mean     2025-06-04 06:00:00
min      2025-05-11 00:00:00
25%      2025-05-24 18:00:00
50%      2025-06-01 00:00:00
75%      2025-06-19 00:00:00
max      2025-07-01 00:00:00
Name: signup_date, dtype: object

Con NPS:
count                     68
mean     2025-06-03 06:00:00
min      2025-05-04 00:00:00
25%      2025-05-19 00:00:00
50%      2025-06-03 00:00:00
75%      2025-06-19 00:00:00
max      2025-07-02 00:00:00
Name: signup_date, dtype: object

Descarto que los valores nulos de NPS corresponden a clientes ingresados recientemente.Dejo los valores nulos para evaluar luego

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
for col in ['industry', 'hq_region', 'plan_tier', 'sales_rep', 'lifecycle_stage', 'marketing_source']:
    print(f"--- {col} ---")
    print(df[col].value_counts())
    print()

--- industry ---
industry
Gaming           12
Education        10
Manufacturing    10
Government        9
Retail            9
Healthcare        8
Fintech           7
E-commerce        6
Energy            5
Media             4
Name: count, dtype: int64

--- hq_region ---
hq_region
eu-central      16
ap-south        15
us-east         14
ap-northeast    11
sa-east         10
us-west          7
eu-west          7
Name: count, dtype: int64

--- plan_tier ---
plan_tier
standard      41
pro           21
enterprise    10
free           8
Name: count, dtype: int64

--- sales_rep ---
sales_rep
rep_d    22
rep_b    18
rep_e    17
rep_a    14
rep_c     9
Name: count, dtype: int64

--- lifecycle_stage ---
lifecycle_stage
active      54
at_risk     11
churned      6
prospect     6
lead         3
Name: count, dtype: int64

--- marketing_source ---
marketing_source
event       21
organic     17
partner     16
ads         14
referral    12
Name: count, dtype: int64

In [32]:
df.to_csv('data/clean/customers_orgs_limpio.csv', index=False)